version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    docker:
      - image: g33tha/node-8.11
    steps:
      - checkout
      - run: sh test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test-cases
