version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: run build file
          command: /bin/bash -x build.sh ${CIRCLE_SHA1} test
  test-cases:
    docker:
      - image: sunbird/build:player
    steps:
      - checkout
      - run: sh test.sh
      - store_artifacts:
          path: /tmp/logs
          
workflows:
  version: 2
  build_and_test:
    jobs:
      #- build
      - test-cases
